root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api ./cmd/api"
bin = "./tmp/api"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "testdata"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true
